### ISSUE TITLE
Better error message for slurpy in the wrong place.

### ISSUE THREAD

**Issue by schwern** [mauke/Function-Parameters#18]
```
$ perl -wle 'use Function::Parameters; fun foo(@that, $this) {}'
In fun foo: I was expecting ")" after "@that", not "$this" at -e line 1.
```

How about "Slurpy @that must come at the end"?

```
$ perl -wle 'use Function::Parameters; fun foo($this, @that, @foo) {}'
In fun foo: I was expecting ")" after "@that", not "@foo" at -e line 1.
```

How about "There is already a slurpy, @that.  @foo is an extra"?

**Comment by mauke** [comment]
I changed the error message. It's not exactly what you suggested but at least it mentions "slurpy parameter" now, which I hope is more helpful.
