### ISSUE TITLE
Slurpies are assumed to be optional

### ISSUE THREAD

**Issue by schwern** [mauke/Function-Parameters#19]
Method::Signatures supports required slurpies.

```
$ perl -MMethod::Signatures -wle 'method foo (@foo!) {} main->foo'
In call to main::foo(), missing required argument @foo at -e line 1.
```

The idea that slurpies are always optional is baked pretty deep into Function::Parameters and I'm having difficulty enforcing the requirement.

**Comment by mauke** [comment]
See #17. It's not that they're optional, it's that they consume a list and lists can be empty.
